# Generated by Django 4.2.19 on 2025-03-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_animal_location_alter_animal_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='image',
        ),
        migrations.AddField(
            model_name='animal',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
