# Generated by Django 4.2.19 on 2025-03-19 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_remove_animal_image_animal_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='image_url',
        ),
        migrations.AddField(
            model_name='animal',
            name='image_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
