# Generated by Django 4.2.19 on 2025-03-19 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0004_remove_animal_image_url_animal_image_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='image_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
